export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const CITY_WEATHER = 'CITY_WEATHER';
export const ERROR_ITEMS = 'ERROR_ITEMS';
export const DELETE_CITY = 'DELETE_CITY';
export const ERROR_NO_MATCHES = 'ERROR_NO_MATCHES';