export const CURRENT_LOCATION_WEATHER = 'CURRENT_LOCATION_WEATHER';
export const CITY_WEATHER = 'CITY_WEATHER';
export const ERROR_ITEMS = 'ERROR_ITEMS';
export const DELETE_CITY = 'DELETE_CITY';
export const ERROR_NO_MATCHES = 'ERROR_NO_MATCHES';
export const ERROR_CLEAR = 'ERROR_CLEAR';
export const ERROR_DENIED_GEOLOCATION = 'ERROR_DENIED_GEOLOCATION';